add download diagnostics feature
skodaconnect/homeassistant-myskoda pull request #415
Opened 2024-12-06 19:09 UTC by prvakt

fixtures can be downloaded directly using `DOWNLOAD DIAGNOSTICS` button from the device page. They will be returned in data object as this is the way how its implemented by HA. There are some other data but nothing private. Tried to return also yaml but no matter what I tried, formatting was always broken as its returned in dictionary. 

And probably we can remove `Generate Fixtures` what do you think?

2024-12-06 19:13 UTC, prvakt commented
Sample report from my test HA instance.. Just ignore those errors from MySkoda - probably banned because of too many logins today 🙈 
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.10.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Bratislava",
    "os_name": "Linux",
    "os_version": "6.6.54-haos",
    "supervisor": "2024.11.4",
    "host_os": "Home Assistant OS 13.2",
    "docker_version": "27.2.0",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "skodaconnect": {
      "documentation": "https://github.com/skodaconnect/homeassistant-skodaconnect/blob/main/README.md",
      "version": "v1.2.12",
      "requirements": [
        "skodaconnect==1.3.11",
        "homeassistant>=2024.4.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "sun2": {
      "documentation": "https://github.com/pnbruckner/ha-sun2/blob/3.3.3/README.md",
      "version": "3.3.3",
      "requirements": []
    },
    "tuya_v2": {
      "documentation": "https://github.com/tuya/tuya-home-assistant",
      "version": "1.5.0",
      "requirements": [
        "tuya-iot-py-sdk==0.4.1"
      ]
    },
    "ecowater_softener": {
      "documentation": "https://github.com/barleybobs/homeassistant-ecowater-softener/",
      "version": "4.1.0",
      "requirements": [
        "ecowater-softener==2.2.1"
      ]
    },
    "solcast_solar": {
      "documentation": "https://github.com/BJReplay/ha-solcast-solar",
      "version": "v4.1.7",
      "requirements": [
        "aiohttp>=3.8.5",
        "aiofiles>=23.2.0",
        "datetime>=4.3",
        "isodate>=0.6.1"
      ]
    },
    "myskoda": {
      "documentation": "https://github.com/skodaconnect/homeassistant-myskoda/blob/main/README.md",
      "version": "1.14.1",
      "requirements": [
        "myskoda==0.14.0"
      ]
    },
    "browser_mod": {
      "documentation": "https://github.com/thomasloven/hass-browser_mod/blob/master/README.md",
      "version": "2.3.1",
      "requirements": []
    },
    "huawei_solar": {
      "documentation": "https://github.com/wlcrs/huawei_solar/wiki",
      "version": "1.4.1",
      "requirements": [
        "huawei-solar==2.3.0"
      ]
    },
    "vesync": {
      "documentation": "https://github.com/micahqcade/custom_vesync",
      "version": "1.3.2",
      "requirements": [
        "pyvesync==2.1.12"
      ]
    },
    "average": {
      "documentation": "https://github.com/Limych/ha-average",
      "version": "2.4.0",
      "requirements": [
        "pip>=21.3.1"
      ]
    },
    "localtuya": {
      "documentation": "https://github.com/rospogrigio/localtuya/",
      "version": "5.2.1",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "myskoda",
    "name": "MySkoda",
    "codeowners": [
      "prior99",
      "WebSpider",
      "dvx76"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/skodaconnect/homeassistant-myskoda/blob/main/README.md",
    "integration_type": "hub",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/skodaconnect/homeassistant-myskoda/issues",
    "loggers": [
      "custom_components.myskoda",
      "myskoda"
    ],
    "requirements": [
      "myskoda==0.14.0"
    ],
    "version": "1.14.1",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 3.8300000596791506e-05
    },
    "01JDS5KK791GN6D9PAR7E95DCD": {
      "wait_import_platforms": -0.009107237012358382,
      "wait_base_component": -0.0003934019769076258,
      "config_entry_setup": 11.814468719996512
    }
  },
  "data": {
    "fixtures": {
      "name": "Superb",
      "description": "Fixtures for Superb L&K 2020",
      "generation_time": "2024-12-06T19:03:19.855018+00:00",
      "library_version": "0.14.0",
      "vehicles": [
        {
          "id": 0,
          "device_platform": "MBB_ODP",
          "system_model_id": "3V55XC",
          "model": "Superb",
          "model_year": "2020",
          "trim_level": "L&K",
          "software_version": null,
          "capabilities": [
            {
              "id": "LOYALTY_PROGRAM",
              "statuses": []
            },
            {
              "id": "SUBSCRIPTIONS",
              "statuses": []
            },
            {
              "id": "CAR_FEEDBACK",
              "statuses": []
            },
            {
              "id": "LOYALTY_PROGRAM_WORLDWIDE",
              "statuses": []
            },
            {
              "id": "OUTSIDE_TEMPERATURE",
              "statuses": []
            },
            {
              "id": "SERVICE_PARTNER",
              "statuses": []
            },
            {
              "id": "MISUSE_PROTECTION",
              "statuses": []
            }
          ]
        }
      ],
      "reports": [
        {
          "type": "get",
          "vehicle_id": 0,
          "success": true,
          "endpoint": "info",
          "raw": "{\"vin\": \"TMOCKAA0AA000000\", \"name\": \"Example Car\", \"workshopModeEnabled\": false, \"licensePlate\": \"HH AA 1234\", \"state\": \"ACTIVATED\", \"devicePlatform\": \"MBB_ODP\", \"specification\": {\"title\": \"\\u0160koda Superb Combi\", \"manufacturingDate\": \"2020-03-05\", \"model\": \"Superb\", \"modelYear\": \"2020\", \"body\": \"Combi\", \"trimLevel\": \"L&K\", \"systemCode\": \"UNKNOWN\", \"systemModelId\": \"3V55XC\", \"battery\": {\"capacityInKWh\": 13}, \"engine\": {\"type\": \"TSI iV\", \"powerInKW\": 160, \"capacityInLiters\": 1.4}, \"gearbox\": {\"type\": \"A6F\"}}, \"servicePartner\": {\"servicePartnerId\": \"DEU11111\"}, \"renders\": [{\"url\": \"https://skodavinimagecache.blob.core.windows.net/cache3v5s20201119/8X8X-_ovsqZUlebk-6kVuox9bcY-24NgnyaQTw.qVlH-xIA7F_6aPQ2EYMU1f-s2BZqeSWgmR0K69.ltbHVNDwO-DiSFcULXOfePZlBGIn-19201080dayvext_front1080.png\", \"viewPoint\": \"exterior_front\", \"type\": \"REAL\", \"order\": 0}, {\"url\": \"https://skodavinimagecache.blob.core.windows.net/cache3v5s20201119/8X8X-_ovsqZUlebk-6kVuox9bcY-24NgnyaQTw.qVlH-xIA7F_6aPQ2EYMU1f-s2BZqeSWgmR0K69.ltbHVNDwO-DiSFcULXOfePZlBGIn-19201080dayvext_side1080.png\", \"viewPoint\": \"exterior_side\", \"type\": \"REAL\", \"order\": 1}, {\"url\": \"https://ip-modcwp.azureedge.net/modcwp3v5s20201119/8X8X-_ovsqZUlebk-6kVuox9bcY-24NgnyaQTw.qVlH-xIA7F_6aPQ2EYMU1f-s2BZqeSWgmR0K69.ltbHVNDwO-DiSFcULXOfePZlBGIn-1920658dayvext_side1080.png?v=638544159110000000\", \"viewPoint\": \"garage_l\", \"type\": \"REAL\", \"order\": 2}, {\"url\": \"https://ip-modcwp.azureedge.net/modcwp3v5s20201119/8X8X-_ovsqWUlebk-6kVu2o9bdY-17NgnyaQTw.qVlH-xIC8F.6aPQ2EXMUzf-s2BZqeSWgmRyK69.ktbHVNDwO-DiSFcTLXOgdPZlAGIn-700390dayvext_front1080.png?v=637869889800000000\", \"viewPoint\": \"main\", \"type\": \"REAL\", \"order\": 3}], \"compositeRenders\": [{\"layers\": [{\"url\": \"https://skodavinimagecache.blob.core.windows.net/cache3v5s20201119/8X8X-_ovsqZUlebk-6kVuox9bcY-24NgnyaQTw.qVlH-xIA7F_6aPQ2EYMU1f-s2BZqeSWgmR0K69.ltbHVNDwO-DiSFcULXOfePZlBGIn-19201080dayvext_front1080.png\", \"viewPoint\": \"exterior_front\", \"type\": \"REAL\", \"order\": 0}], \"viewType\": \"UNMODIFIED_EXTERIOR_FRONT\"}, {\"layers\": [{\"url\": \"https://skodavinimagecache.blob.core.windows.net/cache3v5s20201119/8X8X-_ovsqZUlebk-6kVuox9bcY-24NgnyaQTw.qVlH-xIA7F_6aPQ2EYMU1f-s2BZqeSWgmR0K69.ltbHVNDwO-DiSFcULXOfePZlBGIn-19201080dayvext_side1080.png\", \"viewPoint\": \"exterior_side\", \"type\": \"REAL\", \"order\": 0}], \"viewType\": \"UNMODIFIED_EXTERIOR_SIDE\"}, {\"layers\": [{\"url\": \"https://skodavinimagecache.blob.core.windows.net/cache3v5s20201119/8X8X-_ovsqZUlebk-6kVuox9bcY-24NgnyaQTw.qVlH-xIA7F_6aPQ2EYMU1f-s2BZqeSWgmR0K69.ltbHVNDwO-DiSFcULXOfePZlBGIn-19201080dayvext_side1080. [...]

2024-12-06 21:36 UTC, WebSpider requested changes
Thanks for looking into this! 👍

Could you add a little bit of documentation into README.MD on this feature, the fact that it exist, what it can be used for, how to submit the result to be added to for future testing, etc?

2024-12-06 22:11 UTC, prvakt commented
> Thanks for looking into this! 👍
> 
> Could you add a little bit of documentation into README.MD on this feature, the fact that it exist, what it can be used for, how to submit the result to be added to for future testing, etc?

Yes I will write short info into readme over the weekend. How about the current "Generate Fixtures" button - should we keep it? Both can be used for the same purpose, with the difference that one logs to the HA core log and the other to a file..

2024-12-06 23:07 UTC, WebSpider commented
If this works, we'll remove generate fixtures in a few releases

2024-12-07 17:48 UTC, WebSpider approved these changes
Awesome 👍

2024-12-07 18:48 UTC, merged