Add availability for charging sensor
skodaconnect/homeassistant-myskoda pull request #80
Opened 2024-10-09 10:03 UTC by WebSpider

Fixes #72

2024-10-09 18:03 UTC, dvx76 requested changes

2024-10-09 18:03 UTC, dvx76 commented on custom_components/myskoda/sensor.py
> +        return self._status().state is not None
Can it actually ever be `None`? Since `ChargingStatus._status()` will raise an exception if the status is `None`

2024-10-15 12:26 UTC, WebSpider commented
Better fixes by #93

2024-10-15 12:26 UTC, closed without merging

2024-10-17 07:30 UTC, WebSpider commented
@sonar98 thanks for the feedback!